server:
  port: 8181
spring:
  application:
    name: backend-sat
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:~/test;
    username: sa
    password:
    driverClassName: org.h2.Driver
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    defer-datasource-initialization: true

springdoc:
  packagesToScan: com.backend_sat
